---
steps:
  - label: ':mag: Capture deprecation warnings'
    commands: |-
      # Redirect the shell's outputs a file for processing
      exec > >(tee -a full_build_logs.txt) 2> >(tee -a full_build_logs.txt >&2)

      # Run your various commands
      node --trace-deprecation deprecationWarnings.js

      # Extract uniq deprecation warnings
      grep -iE "deprecation|warning" full_build_logs.txt | sort | uniq > deprecation_warnings.txt

      # Check if there are any deprecation warnings
      if [ -s deprecation_warnings.txt ]; then
        # Create buildkite annotation with the warnings
        buildkite-agent annotate --context "deprecation-warnings" --style "warning" < deprecation_warnings.txt
      else
        echo "No deprecation warnings found."
      fi
